DEFAULT_PRESETS = [
    {
        "id": "document",
        "name": "Document",
        "description": "Everyday paperwork for Paperless",
        "dpi": 300,
        "color_mode": "Gray",
        "page_size": "A4",
        "output_format": "pdf",
        "compression": "medium",
        "enhancement_profile": "clean_document",
        "multi_page": True,
    },
    {
        "id": "receipt",
        "name": "Receipt",
        "description": "Narrow receipts with stronger cleanup",
        "dpi": 300,
        "color_mode": "Gray",
        "page_size": "Auto",
        "output_format": "pdf",
        "compression": "medium",
        "enhancement_profile": "receipt_cleanup",
        "multi_page": False,
    },
    {
        "id": "photo",
        "name": "Photo",
        "description": "Preserve color and detail",
        "dpi": 600,
        "color_mode": "Color",
        "page_size": "Auto",
        "output_format": "jpeg",
        "compression": "high",
        "enhancement_profile": "photo_preservation",
        "multi_page": False,
    },
    {
        "id": "id_card",
        "name": "ID or card",
        "description": "Small cards at high detail",
        "dpi": 600,
        "color_mode": "Color",
        "page_size": "Auto",
        "output_format": "pdf",
        "compression": "medium",
        "enhancement_profile": "preserve_color",
        "multi_page": False,
    },
    {
        "id": "letter",
        "name": "Letter",
        "description": "Letters and official correspondence",
        "dpi": 300,
        "color_mode": "Gray",
        "page_size": "Letter",
        "output_format": "pdf",
        "compression": "medium",
        "enhancement_profile": "clean_document",
        "multi_page": True,
    },
    {
        "id": "archive",
        "name": "High quality archive",
        "description": "Long-term archival copy",
        "dpi": 600,
        "color_mode": "Color",
        "page_size": "A4",
        "output_format": "pdf",
        "compression": "low",
        "enhancement_profile": "clean_document",
        "multi_page": True,
    },
    {
        "id": "quick",
        "name": "Quick scan",
        "description": "Fast low-friction scan",
        "dpi": 200,
        "color_mode": "Gray",
        "page_size": "Auto",
        "output_format": "pdf",
        "compression": "medium",
        "enhancement_profile": "clean_document",
        "multi_page": False,
    },
    {
        "id": "custom",
        "name": "Custom",
        "description": "Manual settings",
        "dpi": 300,
        "color_mode": "Color",
        "page_size": "Auto",
        "output_format": "pdf",
        "compression": "medium",
        "enhancement_profile": "clean_document",
        "multi_page": False,
    },
]

DEFAULT_ENHANCEMENTS = [
    {"id": "clean_document", "name": "Clean document", "deskew": False, "crop_edges": False, "remove_noise": True, "sharpen_text": True, "preserve_color": False},
    {"id": "receipt_cleanup", "name": "Receipt cleanup", "deskew": False, "crop_edges": False, "remove_noise": True, "sharpen_text": True, "preserve_color": False},
    {"id": "photo_preservation", "name": "Photo preservation", "deskew": False, "crop_edges": False, "remove_noise": False, "sharpen_text": False, "preserve_color": True},
    {"id": "high_contrast_bw", "name": "High contrast black and white", "deskew": False, "crop_edges": False, "remove_noise": True, "sharpen_text": True, "preserve_color": False},
    {"id": "preserve_color", "name": "Preserve color", "deskew": False, "crop_edges": False, "remove_noise": False, "sharpen_text": False, "preserve_color": True},
]
